// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe7Z0wwotfPxoio3QspTRRh-MrObvIDJc',
    appId: '1:545836555152:web:4833fce1e513af0b417115',
    messagingSenderId: '545836555152',
    projectId: 'verhuurapp-2de31',
    authDomain: 'verhuurapp-2de31.firebaseapp.com',
    storageBucket: 'verhuurapp-2de31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUgzYXQjLlJ895ZPrEOVw_c9jiNQKUFQw',
    appId: '1:545836555152:android:9bba776bf921c9bf417115',
    messagingSenderId: '545836555152',
    projectId: 'verhuurapp-2de31',
    storageBucket: 'verhuurapp-2de31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3W1tnrWhKC9wJNw82_kHv6RyYU1RPuo',
    appId: '1:545836555152:ios:efe2a0cc9d64299c417115',
    messagingSenderId: '545836555152',
    projectId: 'verhuurapp-2de31',
    storageBucket: 'verhuurapp-2de31.firebasestorage.app',
    iosBundleId: 'com.example.verhuurapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl3W1tnrWhKC9wJNw82_kHv6RyYU1RPuo',
    appId: '1:545836555152:ios:efe2a0cc9d64299c417115',
    messagingSenderId: '545836555152',
    projectId: 'verhuurapp-2de31',
    storageBucket: 'verhuurapp-2de31.firebasestorage.app',
    iosBundleId: 'com.example.verhuurapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe7Z0wwotfPxoio3QspTRRh-MrObvIDJc',
    appId: '1:545836555152:web:3bf0e8f6ec726970417115',
    messagingSenderId: '545836555152',
    projectId: 'verhuurapp-2de31',
    authDomain: 'verhuurapp-2de31.firebaseapp.com',
    storageBucket: 'verhuurapp-2de31.firebasestorage.app',
  );
}
